[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
game = "294LgZBjjo3nbpWF7qxXxK6Wk3dTVtV2vEL9aziZ92To"

[programs.devnet]
game = "294LgZBjjo3nbpWF7qxXxK6Wk3dTVtV2vEL9aziZ92To"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
